# Generated by Django 5.0.6 on 2024-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_socialaccount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
