# Generated by Django 5.0.6 on 2024-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_appuser_is_active_appuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='registered_at',
            field=models.DateTimeField(auto_now=True, verbose_name='가입일'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='마지막 로그인'),
        ),
    ]
